/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }
=======
    
>>>>>>> Stashed changes
=======
    
>>>>>>> Stashed changes
}
